from rpm_service.serializers.Device import DeviceSerializer
from rpm_service.serializers.DeviceProvider import DeviceProviderSerializer
from rpm_service.serializers.ConnectivityType import ConnectivityTypeSerializer
