default:
  page_size: 10
  page_query_param: page
  page_size_query_param: size
  max_page_size: 1000

develop:
  page_size: 10
  page_query_param: page
  page_size_query_param: size
  max_page_size: 1000

test:
  page_size: 5
  page_query_param: page
  page_size_query_param: size
  max_page_size: 1000

